import {spawn} from 'node:child_process';
import {mkdir,writeFile,readdir,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const delay=ms=>new Promise(r=>setTimeout(r,ms)),folder=resolve('artifacts'),port=9343;
await mkdir(folder+'/downloads',{recursive:true});
const browser=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--in-process-gpu','--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader','--no-first-run','--no-default-browser-check','--remote-debugging-port='+port,'--user-data-dir='+resolve('../.steelsmart-browser-'+process.pid),'about:blank'],{windowsHide:true,stdio:'ignore'});
let socket;try{
let targets;for(let i=0;i<80;i++){try{targets=await(await fetch(`http://127.0.0.1:${port}/json`)).json();break;}catch{await delay(200);}}assert.ok(targets,'Browser starts');socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});let id=0;const pending=new Map(),errors=[],downloads=[];socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method?.includes('download'))downloads.push(m);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};
const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id,t=setTimeout(()=>reject(new Error(method+' timeout')),20000);pending.set(n,{resolve:v=>{clearTimeout(t);resolve(v);},reject});socket.send(JSON.stringify({id:n,method,params}));});const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};const until=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await delay(100);}throw new Error('Timed out: '+expression);};const click=id=>evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);const shot=async name=>{if(process.env.CAPTURE!=='1')return;const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(folder+'/'+name+'.png',Buffer.from(r.data,'base64'));};const trustedClick=async selector=>{await evaluate('document.querySelector('+JSON.stringify(selector)+').scrollIntoView({block:"center"})');const p=await evaluate('(()=>{const r=document.querySelector('+JSON.stringify(selector)+').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()');await send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});};const metrics=async(width,height,mobile=false)=>send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile});
await send('Runtime.enable');await send('Page.enable');await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:(folder+'/downloads').replaceAll('\\','/'),eventsEnabled:true});await metrics(1512,1100);await send('Page.navigate',{url:'http://localhost:4310/studio.html'});await until("document.documentElement?.dataset.ready==='true'");await evaluate('document.fonts.ready');await delay(1300);
assert.equal(await evaluate("document.getElementById('viewport-error').hidden"),true,'WebGL initialized');assert.ok(await evaluate("(()=>{const c=document.createElement('canvas');c.width=100;c.height=100;const ctx=c.getContext('2d');ctx.drawImage(document.getElementById('scene'),0,0,100,100);const data=ctx.getImageData(0,0,100,100).data,colors=new Set();for(let i=0;i<data.length;i+=4)colors.add(data[i]+','+data[i+1]+','+data[i+2]);return colors.size})()")>30,'3D canvas contains rendered geometry');assert.equal(await evaluate("document.querySelectorAll('#bom-body tr').length"),4);assert.equal(await evaluate('document.documentElement.scrollWidth>innerWidth'),false);await shot('desktop');
await evaluate("document.getElementById('prompt').value='A warehouse 24m wide, 36m long and 8m high with 6 bays';document.getElementById('prompt-form').requestSubmit()");await until("document.getElementById('width').value==='24'");assert.equal(await evaluate("document.getElementById('bays').value"),'6');await evaluate("document.getElementById('width').value=30;document.getElementById('width').dispatchEvent(new Event('input'));document.getElementById('width').dispatchEvent(new Event('change'))");assert.match(await evaluate("document.getElementById('area').textContent"),/1,080/);await click('undo');assert.equal(await evaluate("document.getElementById('width').value"),'24');await evaluate("document.getElementById('width-number').focus();document.getElementById('width-number').select()");await send('Input.insertText',{text:'1'});assert.equal(await evaluate("document.getElementById('width-number').value"),'1');await send('Input.insertText',{text:'2'});assert.equal(await evaluate("document.getElementById('width-number').value"),'12');await evaluate("document.getElementById('width-number').blur()");assert.equal(await evaluate("document.getElementById('width').value"),'12');await click('undo');
await evaluate("document.getElementById('prompt').value='<img src=x onerror=alert(1)> spaceship';document.getElementById('prompt-form').requestSubmit()");assert.equal(await evaluate("document.getElementById('prompt-feedback').classList.contains('error')"),true);assert.equal(await evaluate("document.querySelector('#prompt-feedback img')"),null);
await evaluate("document.querySelector('[data-preset=canopy]').click()");assert.equal(await evaluate("document.getElementById('template').value"),'canopy');assert.equal(await evaluate("document.getElementById('pitch').disabled"),true);await evaluate("document.querySelector('[data-preset=rack]').click()");assert.equal(await evaluate("document.getElementById('template').value"),'rack');await click('tab-checks');assert.equal(await evaluate("document.getElementById('panel-checks').hidden"),false);await click('tab-notes');assert.equal(await evaluate("document.getElementById('panel-notes').hidden"),false);await click('tab-bom');
await click('wireframe');assert.equal(await evaluate("document.getElementById('wireframe').getAttribute('aria-pressed')"),'true');await click('wireframe');await click('explode');await delay(250);await shot('exploded');await click('explode');await evaluate("document.querySelector('[data-view=top]').click()");await evaluate("document.querySelector('[data-view=perspective]').click()");
await evaluate("window.exportBlobs=[];const original=URL.createObjectURL.bind(URL);URL.createObjectURL=blob=>{window.exportBlobs.push(blob);return original(blob)}");await click('export-open');assert.equal(await evaluate("document.getElementById('export-dialog').open"),true);await trustedClick('[data-export=obj]');await trustedClick('#csv-export');await click('export-open');await trustedClick('[data-export=json]');const payloads=await evaluate("Promise.all(window.exportBlobs.map(blob=>blob.text()))");assert.equal(payloads.length,3,'Three actual export blobs');assert.match(payloads[0],/^o /m);assert.match(payloads[1],/Member,Profile,Quantity/);const json=JSON.parse(payloads[2]);assert.equal(json.params.template,'rack');assert.ok(json.members.length>10);for(const [i,ext] of ['obj','csv','json'].entries())await writeFile(folder+'/verified-export.'+ext,payloads[i]);if(process.env.WRITE_DOWNLOADS==='1'){await delay(1500);const files=await readdir(folder+'/downloads');for(const ext of ['obj','csv','json'])assert.ok(files.some(f=>f.endsWith('.'+ext)),ext+' browser file download');}else console.log('Export blob bytes verified; OS-level download finalization is a separate WRITE_DOWNLOADS=1 check.');
await send('Page.reload');await until("document.documentElement?.dataset.ready==='true'");assert.equal(await evaluate("document.getElementById('template').value"),'rack');await evaluate("document.querySelector('[data-nav=library]').click()");assert.equal(await evaluate("document.querySelectorAll('.library-part').length"),5);await evaluate("document.querySelector('#info-dialog .close-dialog').click()");await evaluate("document.querySelector('[data-nav=projects]').click()");assert.ok(await evaluate("document.querySelectorAll('.saved-design').length")>1);await evaluate("document.querySelector('#info-dialog .close-dialog').click()");await evaluate("document.querySelector('[data-preset=portal]').click()");
for(const width of [768,390]){await metrics(width,1000,width===390);await evaluate('window.scrollTo(0,0)');await delay(300);assert.equal(await evaluate('document.documentElement.scrollWidth>innerWidth'),false,'No overflow '+width);await shot(width===390?'mobile':'tablet');}
await metrics(1512,1100);await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await evaluate("localStorage.setItem('steelsmart-v1','{broken')");await send('Page.reload');await until("document.documentElement?.dataset.ready==='true'");assert.equal(await evaluate("document.getElementById('width').value"),'18');assert.deepEqual(errors,[]);console.log('PASS: WebGL, generation, parameters, undo, unsupported/injection-safe prompts, templates, tabs, wireframe, explosion, named views, OBJ/CSV/JSON export payloads, persistence, corrupt-state recovery, library, history, desktop/tablet/mobile and no JS exceptions.');
}finally{socket?.close();browser.kill();browser.unref();}
