import {DEFAULTS,normalize,buildAssembly,parsePrompt,billOfMaterials,exportOBJ,exportCSV,PROFILES} from './model.js';
import {SteelViewport} from './scene.js';
import {StudioWorkbench} from './studio-workbench.js';
import {createFrameTask} from './ui-scheduler.js';
const $=id=>document.getElementById(id),fmt=n=>Math.round(n).toLocaleString('en-US'),names={column:'Primary columns',rafter:'Roof rafters',purlin:'Roof purlins',brace:'Cross bracing',beam:'Horizontal beams'};
let state={...DEFAULTS},history=[],model,viewport,workbench,version=1,storageOK=true;
let renderedKey='';const scheduleRender=createFrameTask(()=>render());
try{const saved=JSON.parse(localStorage.getItem('steelsmart-v1'));if(saved&&typeof saved==='object'){state=normalize(saved.params);history=Array.isArray(saved.history)?saved.history.filter(h=>h&&typeof h.label==='string'&&h.params).slice(-8).map(h=>({...h,params:normalize(h.params)})):[];version=Math.max(1,Math.min(999,Number(saved.version)||1));}}catch{storageOK=false;}
const incoming=new URLSearchParams(location.search);if(incoming.get('from')==='playground'){const imported=Object.fromEntries(incoming);state=normalize({...imported,bracing:imported.bracing!=='false'});history.push({label:'From the playground',params:{...state},time:Date.now()});history=history.slice(-8);version++;window.history.replaceState({},'',location.pathname);}
if(!history.length)history=[{label:'Initial concept',params:{...state},time:Date.now()}];
const controls=[['width','Span / width',6,36,1,'m'],['length','Building length',6,60,1,'m'],['height','Eave height',3,12,.5,'m'],['bays','Number of bays',2,8,1,''],['pitch','Roof pitch',5,30,1,'°']];
for(const [id,label,min,max,step,unit] of controls){const wrapper=document.createElement('div');wrapper.className='dimension-control';wrapper.innerHTML=`<div class="control-top"><label for="${id}">${label}</label><span class="number-wrap"><input id="${id}-number" type="number" aria-label="${label}" min="${min}" max="${max}" step="${step}"><span>${unit}</span></span></div><input type="range" id="${id}" aria-label="${label}" min="${min}" max="${max}" step="${step}"><div class="range-ends"><span>${min}${unit}</span><span>${max}${unit}</span></div>`;$('dimension-controls').append(wrapper);for(const input of [$(id),$(id+'-number')]){input.addEventListener('input',()=>{if(input.type==='number'||input.value==='')return;state=normalize({...state,[id]:Number(input.value)});$(id+'-number').value=state[id];scheduleRender();});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&input.type==='number')input.blur();});input.addEventListener('change',()=>{state=normalize({...state,[id]:input.value===''?state[id]:Number(input.value)});record('Updated '+label.toLowerCase());render();});}}
try{viewport=new SteelViewport($('scene'),$('viewport'),member=>{workbench?.onSelection(member);const el=$('selection');el.hidden=!member;if(member){el.replaceChildren();const strong=document.createElement('strong');strong.textContent=member.id;const text=document.createTextNode(`${names[member.kind]} · ${member.profile}`),small=document.createElement('small');small.textContent=`Length ${member.length.toFixed(2)} m · Mass ${member.mass.toFixed(1)} kg · ${state.material}`;el.append(strong,text,small);}});}catch(error){$('viewport-error').hidden=false;$('viewport-error').textContent='The 3D view needs WebGL. Enable hardware acceleration or try another browser. Parameters, material schedules and exports are still available.';console.warn('WebGL unavailable:',error.message);}
function persist(){try{localStorage.setItem('steelsmart-v1',JSON.stringify({params:state,history,version}));storageOK=true;}catch{storageOK=false;}if(!storageOK)$('model-status').textContent='Session only · storage unavailable';}
function record(label){version++;history.push({label,params:{...state},time:Date.now()});history=history.slice(-8);}
function render(){scheduleRender.cancel();const nextKey=JSON.stringify(state),changed=!model||nextKey!==renderedKey;if(changed){model=buildAssembly(state);state=model.params;renderedKey=JSON.stringify(state);}for(const [id] of controls){$(id).value=state[id];$(id+'-number').value=state[id];}for(const id of ['template','material'])$(id).value=state[id];$('bracing').checked=state.bracing;$('pitch').disabled=state.template!=='portal';$('pitch-number').disabled=state.template!=='portal';$('model-title').replaceChildren(document.createTextNode(state.name));const small=document.createElement('small');small.innerHTML='<span class="status-dot"></span>Parametric model <span class="model-version"></span>';small.lastElementChild.textContent='v'+version;$('model-title').append(small);$('drawing-id').textContent='SS–'+String(version).padStart(3,'0');$('member-count').textContent=model.members.length+' members';$('area').innerHTML=`${fmt(model.area)} <small>m²</small>`;$('mass').innerHTML=`${fmt(model.mass)} <small>kg</small>`;$('beam-profile').textContent=state.template==='portal'?'IPE 300':'IPE 240';const bom=billOfMaterials(model);$('bom-count').textContent=bom.length;$('bom-body').innerHTML=bom.map(r=>`<tr><td><span class="component-dot dot-${r.kind}"></span>${names[r.kind]}</td><td>${r.profile}</td><td>${r.quantity} pcs</td><td>${r.length.toFixed(1)} m</td><td>${fmt(r.mass)} kg</td><td><span>${state.material}</span></td></tr>`).join('');$('total-mass').textContent='Total member mass  '+fmt(model.mass)+' kg';$('panel-checks').innerHTML=`<h3>Geometry you can inspect.</h3><div class="check-row"><span>Finite member coordinates</span><span>Passed · ${model.members.length} members</span></div><div class="check-row"><span>Positive member lengths</span><span>Passed</span></div><div class="check-row"><span>Material schedule matches geometry</span><span>Passed</span></div><div class="check-row"><span>Supported dimensional bounds</span><span>Passed</span></div><div class="check-row"><span>Load capacity / building code compliance</span><span>Not evaluated</span></div><p>These are model consistency checks. Structural adequacy, foundations, connections, wind and seismic loads require an engineer’s assessment.</p>`;renderHistory();if(changed){viewport?.update(model);workbench?.update(model);}$('model-status').textContent='Geometry ready';persist();}
function renderHistory(){$('history').replaceChildren();history.slice(-3).reverse().forEach((entry,index)=>{const b=document.createElement('button');b.className='history-item';const dot=document.createElement('span'),text=document.createElement('span');text.textContent=entry.label;const small=document.createElement('small');small.textContent=`${entry.params.width} × ${entry.params.length} m · ${entry.params.bays} bays`;text.append(small);b.append(dot,text);if(index===0){const tag=document.createElement('span');tag.className='history-current';tag.textContent='Current';b.append(tag);}b.addEventListener('click',()=>{state={...entry.params};record('Restored concept');render();toast('Design restored');});$('history').append(b);});$('undo').disabled=history.length<2;}
function feedback(text,error=false){$('prompt-feedback').hidden=false;$('prompt-feedback').textContent=text;$('prompt-feedback').classList.toggle('error',error);}
let generating=false;
$('prompt-form').addEventListener('submit',e=>{e.preventDefault();if(generating)return;const result=parsePrompt($('prompt').value,state);if(!result.ok){feedback(result.error,true);return;}generating=true;$('generate').disabled=true;$('generate').textContent='Building member geometry…';state=result.params;record('Generated '+({portal:'portal frame',canopy:'canopy',rack:'storage rack'}[state.template]));render();feedback('Model generated. '+result.summary);$('generate').innerHTML='<svg><use href="#i-spark"/></svg>Generate design<svg><use href="#i-arrow"/></svg>';$('generate').disabled=false;generating=false;});
$('prompt').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')$('prompt-form').requestSubmit();});
const presets={portal:{...DEFAULTS},canopy:{...DEFAULTS,template:'canopy',name:'Open steel canopy',width:12,length:18,height:4,bays:3},rack:{...DEFAULTS,template:'rack',name:'Industrial storage rack',width:6,length:12,height:6,bays:3}};
document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>{state={...presets[button.dataset.preset]};$('prompt').value=`A ${state.name.toLowerCase()}, ${state.width}m wide, ${state.length}m long and ${state.height}m high, with ${state.bays} bays and cross bracing.`;record('Loaded '+state.name.toLowerCase());render();feedback('Template loaded. Adjust the parameters or refine your brief.');}));
for(const id of ['template','material','bracing'])$(id).addEventListener('change',()=>{state[id]=id==='bracing'?$(id).checked:$(id).value;if(id==='template')state.name=presets[state.template].name;record('Updated '+id);render();});
$('undo').addEventListener('click',()=>{if(history.length<2)return;history.pop();state={...history.at(-1).params};version++;render();toast('Previous design restored');});
$('new-design').addEventListener('click',()=>{state={...DEFAULTS};record('New portal frame');$('prompt').value='';$('prompt-feedback').hidden=true;render();toast('New design ready. Previous concepts remain in your history.');});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(b=>{const selected=b===button;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);});viewport?.setView(button.dataset.view);}));
$('fit').addEventListener('click',()=>viewport?.fit());for(const [id,method] of [['wireframe','setWireframe'],['explode','setExploded'],['dimensions','setDimensions']])$(id).addEventListener('click',()=>{const v=$(id).getAttribute('aria-pressed')!=='true';$(id).setAttribute('aria-pressed',v);viewport?.[method](v);});
$('rotate').addEventListener('click',()=>{const v=$('rotate').getAttribute('aria-pressed')!=='true';$('rotate').setAttribute('aria-pressed',v);if(viewport)viewport.auto=v;});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches){if(viewport)viewport.auto=false;$('rotate').setAttribute('aria-pressed','false');}});
const tabs=[...document.querySelectorAll('[data-tab]')];function activateTab(button){tabs.forEach(b=>{const active=b===button;b.classList.toggle('selected',active);b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;$('panel-'+b.dataset.tab).hidden=!active;});}tabs.forEach((button,i)=>{button.tabIndex=i===0?0:-1;button.addEventListener('click',()=>activateTab(button));button.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;activateTab(tabs[index]);tabs[index].focus();}});});
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function download(format){scheduleRender.flush();const content=format==='obj'?exportOBJ(model):format==='csv'?exportCSV(model):JSON.stringify({schema:'steelsmart-assembly-v1',units:'metres',scope:'concept geometry; not certified for fabrication',...model},null,2);const blob=new Blob([content],{type:format==='json'?'application/json':format==='csv'?'text/csv':'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`steelsmart-${state.template}-v${version}.${format}`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);toast(`${format.toUpperCase()} export downloaded`);}
$('export-open').addEventListener('click',()=>$('export-dialog').showModal());$('csv-export').addEventListener('click',()=>download('csv'));document.querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',()=>{download(b.dataset.export);$('export-dialog').close();}));document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
function info(title,html){$('info-title').textContent=title;$('info-content').innerHTML=html;$('info-dialog').showModal();}
const engineInfo=()=>info('A transparent generation engine.','<p>This showcase uses a local, deterministic language parser to turn a supported brief into a parametric member graph. It does not call an LLM or send your text to a server.</p><h3>Try a specific brief</h3><p>“A warehouse 24m wide, 36m long and 8m high with 6 bays and 20 degree roof pitch.”</p><p>It understands portal frames, canopies, racks, dimensions in metres, bays, pitch, S235/S355 steel and bracing. Unsupported requests return a helpful message. The generated geometry, quantities and downloads are real.</p>');$('engine-info').addEventListener('click',engineInfo);
const help=()=>info('Explore your next structure.','<h3>Design in three steps</h3><p>Choose a starting point or describe a supported structure. Change dimensions in the Parameters panel. Export the assembly or its material schedule.</p><h3>Get closer</h3><p>Drag the model to orbit. Scroll to zoom. Click a member to inspect it. With the viewport focused, use arrow keys to rotate, +/− to zoom, and Home to reset. The layer tool separates the assembly.</p><h3>Your workspace</h3><p>Designs are saved in this browser. My designs restores previous concepts. No account or remote service is required.</p>');$('help').addEventListener('click',help);$('viewport-help').addEventListener('click',help);
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.nav==='design'){$('viewport').focus();return;}if(b.dataset.nav==='library'){info('The parts behind the structure.','<p>Nominal sections used by this concept generator. Select a member in the viewport to see its assigned profile.</p><div class="library-grid">'+Object.entries(PROFILES).map(([kind,p])=>`<div class="library-part"><svg viewBox="0 0 80 60" aria-hidden="true">${kind==='brace'?'<circle cx="40" cy="28" r="21"/><circle cx="40" cy="28" r="16"/>':kind==='purlin'?'<rect x="14" y="10" width="52" height="36"/><rect x="19" y="15" width="42" height="26"/>':'<path d="M18 7h44v7H44v29h18v7H18v-7h18V14H18Z"/>'}</svg><strong>${p.name}</strong><small>${p.mass} kg/m · ${names[kind]}</small></div>`).join('')+'</div>');}else{info('Your design collection.','<p>Stored locally in this browser. Restore any of your last eight design revisions.</p><div id="saved-list"></div>');history.slice().reverse().forEach(entry=>{const row=document.createElement('div');row.className='saved-design';const text=document.createElement('span');text.textContent=entry.label;const small=document.createElement('small');small.textContent=`${entry.params.name} · ${entry.params.width} × ${entry.params.length} m`;text.append(small);const button=document.createElement('button');button.textContent='Restore';button.addEventListener('click',()=>{state={...entry.params};record('Restored concept');render();$('info-dialog').close();toast('Design restored');});row.append(text,button);$('saved-list').append(row);});}}));
workbench=new StudioWorkbench({getModel:()=>model,getParams:()=>state,getViewport:()=>viewport&&!viewport.contextLost?viewport:null,applyDesign:(params,label)=>{state=normalize(params);record(label);render();},notify:toast});
document.addEventListener('click',event=>{if(event.target.closest('button,a'))scheduleRender.flush();},{capture:true});
function syncViewportAvailability(){const available=!!viewport&&!viewport.contextLost;for(const id of ['fit','rotate','wireframe','explode','dimensions'])$(id).disabled=!available;document.querySelectorAll('[data-view]').forEach(button=>button.disabled=!available);}
$('scene').addEventListener('viewportavailability',()=>{syncViewportAvailability();workbench?.update(model);});
syncViewportAvailability();render();document.documentElement.dataset.ready='true';
