import {createFrameTask} from './ui-scheduler.js';
import {Sculpture} from './experience-scene.js';
import {storyState,projectConfig,clamp} from './experience-math.js';
import {buildAssembly} from './model.js';
import {DesignLab} from './design-lab.js';
import {readDesignLink} from './lab-model.js';

const $=id=>document.getElementById(id),motion=matchMedia('(prefers-reduced-motion: reduce)'),story=$('story'),copies=[...document.querySelectorAll('[data-chapter]')];
const sharedDesign=readDesignLink(location.search);
const scheduleConfig=createFrameTask(()=>renderConfig());
let lab,hero,playground,params=sharedDesign||projectConfig('portal'),manualExplosion=null,chapter=0,rafPending=false,lastProgress=-1;
function sceneAvailability(kind,available){for(const id of [kind+'-wire',kind+'-touch',...(kind==='hero'?['hero-explode']:[])])$(id).disabled=!available;if(kind==='hero')document.querySelectorAll('[data-finish]').forEach(button=>button.disabled=!available);if(kind==='playground'&&lab){document.querySelectorAll('[data-lab-mode]').forEach(button=>button.disabled=!available);$('lab-save').disabled=!available;if(!available)lab.pause();}}
function fallback(wrap){wrap.classList.add('render-failed');wrap.querySelector('.canvas-fallback').hidden=false;sceneAvailability(wrap.id==='sculpture-wrap'?'hero':'playground',false);}
sceneAvailability('playground',false);
for(const kind of ['hero','playground'])$(kind+'-canvas').addEventListener('sculptureavailability',event=>{sceneAvailability(kind,event.detail);if(kind==='playground'&&event.detail)lab?.sceneReady();});
try{hero=new Sculpture($('hero-canvas'));}catch(error){fallback($('sculpture-wrap'));console.warn('Hero renderer unavailable:',error.message);}

function setChapter(index){chapter=index;story.dataset.chapter=String(index);copies.forEach((copy,i)=>{copy.classList.toggle('is-current',i===index);copy.setAttribute('aria-hidden',i!==index);copy.inert=i!==index;});document.querySelectorAll('[data-jump]').forEach((button,i)=>{button.classList.toggle('active',i===index);if(i===index)button.setAttribute('aria-current','step');else button.removeAttribute('aria-current');});$('model-caption-title').textContent=['THE CONNECTION','THE DETAIL','THE SYSTEM'][index];$('model-caption-sub').textContent=['Steel, considered from every angle.','Each part. A purpose.','One brief. A complete member graph.'][index];}
function updateStory(force=false){rafPending=false;if(motion.matches&&!force)return;const progress=motion.matches?[0,.48,.96][chapter]:clamp(-story.getBoundingClientRect().top/Math.max(1,story.offsetHeight-innerHeight));if(Math.abs(progress-lastProgress)<.0001&&!force)return;lastProgress=progress;const state=storyState(progress);if(state.chapter!==chapter||force)setChapter(state.chapter);hero?.setProgress(state);if(manualExplosion!==null)hero?.setExplosion(manualExplosion);else{$('hero-explode').setAttribute('aria-pressed',state.explosion>.5);$('hero-explode').querySelector('span').textContent=state.explosion>.5?'Bring it together':'Take it apart';}document.querySelector('.story-progress i').style.transform=`scaleX(${progress})`;}
function onScroll(){manualExplosion=null;if(!rafPending){rafPending=true;requestAnimationFrame(()=>updateStory());}}
window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',()=>updateStory(true));document.addEventListener('visibilitychange',()=>{if(!document.hidden){hero?.invalidate();playground?.invalidate();}});
document.querySelectorAll('[data-jump]').forEach(button=>button.addEventListener('click',()=>{manualExplosion=null;$('hero-explode').setAttribute('aria-pressed','false');$('hero-explode').querySelector('span').textContent='Take it apart';const i=Number(button.dataset.jump);if(motion.matches){setChapter(i);updateStory(true);}else{const top=window.scrollY+story.getBoundingClientRect().top;window.scrollTo({top:top+[0,.48,.93][i]*(story.offsetHeight-innerHeight),behavior:'smooth'});}}));
$('hero-explode').addEventListener('click',()=>{manualExplosion=$('hero-explode').getAttribute('aria-pressed')==='true'?0:1;$('hero-explode').setAttribute('aria-pressed',!!manualExplosion);$('hero-explode').querySelector('span').textContent=manualExplosion?'Bring it together':'Take it apart';hero?.setExplosion(manualExplosion);});
function wire(id,getScene){$(id).addEventListener('click',()=>{const enabled=$(id).getAttribute('aria-pressed')!=='true';$(id).setAttribute('aria-pressed',enabled);getScene()?.setWire(enabled);});}
wire('hero-wire',()=>hero);wire('playground-wire',()=>playground);
document.querySelectorAll('[data-finish]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-finish]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});hero?.setFinish(button.dataset.finish);}));
let toastTimer;function note(text){$('interaction-note').textContent=text;$('interaction-note').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('interaction-note').hidden=true,3000);}
function touchMode(id,wrap){$(id).addEventListener('click',()=>{const active=$(id).getAttribute('aria-pressed')!=='true';$(id).setAttribute('aria-pressed',active);$(wrap).dataset.touchOrbit=String(active);note(active?'Drag the model to rotate. Tap Rotate again to scroll.':'Touch scrolling restored.');});}
touchMode('hero-touch','sculpture-wrap');touchMode('playground-touch','playground-canvas-wrap');

const labels={portal:['Portal frame','Room for big ideas.','A portal frame that grows with your ambition. Choose a span. Find your proportions.'],canopy:['Open canopy','A little room to breathe.','Open on every side. Explore a lightweight steel canopy with proportions that are entirely yours.'],rack:['Storage structure','Make more of your space.','Three levels, one editable frame. Find a footprint and height for your next storage concept.']};
function renderConfig(){scheduleConfig.cancel();document.querySelectorAll('[data-template]').forEach(button=>{const active=button.dataset.template===params.template;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active);});const model=playground?playground.buildStructure(params):buildAssembly(params);$('drawing-name').textContent=labels[params.template][0];$('config-name').textContent=labels[params.template][1];$('config-description').textContent=labels[params.template][2];$('drawing-dimensions').textContent=`${params.width} × ${params.length} × ${params.height} m`;for(const k of ['width','length','height']){$('config-'+k).value=params[k];$('output-'+k).value=params[k];}$('config-members').textContent=model.members.length;$('config-mass').replaceChildren(document.createTextNode(Math.round(model.mass).toLocaleString('en-US')));const unit=document.createElement('span');unit.textContent=' kg';$('config-mass').append(unit);const query=new URLSearchParams({from:'playground',template:params.template,width:params.width,length:params.length,height:params.height,bays:params.bays,pitch:params.pitch,material:params.material,bracing:String(params.bracing)});$('continue-design').href='studio.html?'+query;lab?.update(params,model);}
document.querySelectorAll('[data-template]').forEach(button=>button.addEventListener('click',()=>{params=projectConfig(button.dataset.template);document.querySelectorAll('[data-template]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});renderConfig();}));
for(const key of ['width','length','height']){const input=$('config-'+key);input.addEventListener('input',()=>{params[key]=Number(input.value);$('output-'+key).value=params[key];scheduleConfig();});input.addEventListener('change',()=>scheduleConfig.flush());}
document.addEventListener('click',event=>{if(event.target.closest('button,a'))scheduleConfig.flush();},{capture:true});
const lazy=new IntersectionObserver(entries=>{if(!entries.at(-1).isIntersecting)return;lazy.disconnect();try{playground=new Sculpture($('playground-canvas'),{mode:'structure'});sceneAvailability('playground',true);renderConfig();lab.sceneReady();$('playground').dataset.ready='true';}catch(error){fallback($('playground-canvas-wrap'));console.warn('Playground renderer unavailable:',error.message);}},{rootMargin:'450px'});lazy.observe($('playground'));
motion.addEventListener('change',e=>{if(hero)hero.reduced=e.matches;if(playground)playground.reduced=e.matches;lastProgress=-1;if(e.matches)setChapter(0);updateStory(true);});
$('back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:motion.matches?'instant':'smooth'}));
lab=new DesignLab({getScene:()=>playground&&!playground.contextLost?playground:null,getParams:()=>params,notify:note});
renderConfig();setChapter(0);updateStory(true);
if(sharedDesign)requestAnimationFrame(()=>$('playground').scrollIntoView({behavior:'instant'}));document.documentElement.dataset.experienceReady='true';
