export const DEFAULTS={template:'portal',width:18,length:24,height:6,bays:4,pitch:18,bracing:true,material:'S355',name:'Portal frame warehouse'};
const limits={width:[6,36],length:[6,60],height:[3,12],bays:[2,8],pitch:[5,30]};
export function normalize(input={}){const p={...DEFAULTS};for(const [k,[lo,hi]] of Object.entries(limits)){const n=Number(input[k]??p[k]);p[k]=Number.isFinite(n)?Math.max(lo,Math.min(hi,n)):p[k];}p.bays=Math.round(p.bays);p.template=['portal','canopy','rack'].includes(input.template)?input.template:'portal';p.material=['S235','S355'].includes(input.material)?input.material:'S355';p.bracing=input.bracing!==false;p.name=typeof input.name==='string'?input.name.slice(0,80):({portal:'Portal frame warehouse',canopy:'Open steel canopy',rack:'Industrial storage rack'}[p.template]);return p;}
export const PROFILES={column:{name:'HEA 240',depth:.23,width:.24,web:.0075,flange:.012,mass:60.3},rafter:{name:'IPE 300',depth:.30,width:.15,web:.0071,flange:.0107,mass:42.2},purlin:{name:'RHS 100 × 60',depth:.1,width:.06,web:.004,flange:.004,mass:9.2},brace:{name:'CHS 48.3 × 3.2',depth:.048,width:.048,web:.0032,flange:.0032,mass:3.56},beam:{name:'IPE 240',depth:.24,width:.12,web:.0062,flange:.0098,mass:30.7}};
export function buildAssembly(input){const p=normalize(input),members=[],plates=[];let i=0;const add=(kind,a,b)=>{const profile=PROFILES[kind],length=Math.hypot(...a.map((v,j)=>v-b[j]));members.push({id:`${kind.slice(0,1).toUpperCase()}${String(++i).padStart(3,'0')}`,kind,profile:profile.name,a,b,length,mass:length*profile.mass});};const {width:w,length:l,height:h,bays:n}=p,rise=p.template==='portal'?Math.tan(p.pitch*Math.PI/180)*w/2:0;
  for(let j=0;j<=n;j++){const z=-l/2+j*l/n;for(const x of [-w/2,w/2]){add('column',[x,0,z],[x,h,z]);plates.push({position:[x,.025,z],type:'base'});}if(p.template==='portal'){add('rafter',[-w/2,h,z],[0,h+rise,z]);add('rafter',[0,h+rise,z],[w/2,h,z]);}else{add('beam',[-w/2,h,z],[w/2,h,z]);if(p.template==='rack')for(let level=1;level<3;level++)add('beam',[-w/2,h*level/3,z],[w/2,h*level/3,z]);}}
  for(let j=0;j<n;j++){const z=-l/2+j*l/n,z2=z+l/n;for(let k=0;k<=6;k++){const x=-w/2+k*w/6,y=h+rise*(1-Math.abs(x)/(w/2));add('purlin',[x,y,z],[x,y,z2]);}if(p.template==='rack'){for(const x of [-w/2,w/2])for(let level=1;level<3;level++)add('beam',[x,h*level/3,z],[x,h*level/3,z2]);}if(p.bracing&&(j===0||j===n-1)){for(const x of [-w/2,w/2]){add('brace',[x,.3,z],[x,h-.2,z2]);add('brace',[x,h-.2,z],[x,.3,z2]);}add('brace',[-w/2,h,z],[w/2,h,z2]);add('brace',[w/2,h,z],[-w/2,h,z2]);}}
  return {params:p,members,plates,mass:members.reduce((s,m)=>s+m.mass,0),rise,area:w*l};
}
export function billOfMaterials(m){return Object.keys(PROFILES).map(kind=>{const all=m.members.filter(x=>x.kind===kind);return {kind,profile:PROFILES[kind].name,quantity:all.length,length:all.reduce((s,x)=>s+x.length,0),mass:all.reduce((s,x)=>s+x.mass,0)};}).filter(x=>x.quantity);}
export function parsePrompt(text,current=DEFAULTS){const s=String(text).toLowerCase().trim();if(!s)return {ok:false,error:'Describe a portal frame, canopy, or storage rack to get started.'};if(/\b(?:feet|foot|ft|inches|inch|cm|mm|centimet(?:er|re)s?|millimet(?:er|re)s?)\b|[??]/.test(s))return {ok:false,error:'Use metres for dimensions in this demo. Convert feet, inches, cm or mm before generating.'};const p={...normalize(current)},changes=[];let recognized=false;for(const [pattern,template] of [[/warehouse|portal|shed|industrial building/,'portal'],[/canopy|pergola|carport/,'canopy'],[/rack|shelving/,'rack']])if(pattern.test(s)){p.template=template;recognized=true;p.name={portal:'Portal frame warehouse',canopy:'Open steel canopy',rack:'Industrial storage rack'}[template];changes.push(p.name);}
  for(const [key,label,adj] of [['width','width','wide'],['length','length','long'],['height','height','high|tall']]){const match=s.match(new RegExp(`(-?\\d+(?:\\.\\d+)?)\\s*(?:m|metres?|meters?)?\\s*(?:${adj})\\b`))||s.match(new RegExp(`${label}\\s*(?:of|:|=)?\\s*(-?\\d+(?:\\.\\d+)?)`));if(match){p[key]=Number(match[1]);changes.push(`${label} ${p[key]} m`);recognized=true;}}
  const dimensions=s.match(/(\d+(?:\.\d+)?)\s*(?:m)?\s*[x×]\s*(\d+(?:\.\d+)?)\s*(?:m)?(?:\s*[x×]\s*(\d+(?:\.\d+)?))?/);if(dimensions){p.width=+dimensions[1];p.length=+dimensions[2];if(dimensions[3])p.height=+dimensions[3];recognized=true;changes.push('dimensions from brief');}
  const bays=s.match(/(\d+)\s*bays?/);if(bays){p.bays=+bays[1];recognized=true;changes.push(`${p.bays} bays`);}const pitch=s.match(/(-?\d+(?:\.\d+)?)\s*(?:°|degrees?)/);if(pitch){p.pitch=+pitch[1];recognized=true;changes.push(`${p.pitch}° pitch`);}if(/without brac|no brac|remove brac/.test(s)){p.bracing=false;recognized=true;changes.push('bracing removed');}else if(/brac/.test(s)){p.bracing=true;recognized=true;changes.push('cross bracing');}if(/s235|s355/.test(s)){p.material=s.includes('s235')?'S235':'S355';recognized=true;}
  if(!recognized)return {ok:false,error:'This local demo understands portal frames, canopies and racks, metric dimensions, bays, roof pitch and bracing. Try “24m wide warehouse with 6 bays”.'};const params=normalize(p);const clamped=Object.keys(limits).filter(k=>params[k]!==p[k]);return {ok:true,params,summary:changes.join(' · ')+(clamped.length?` · adjusted ${clamped.join(', ')} to supported range`:'' )};}
// Oriented beam envelopes are shared by portable mesh export. All coordinates are metres.
export function memberBasis(m){const d=m.b.map((v,i)=>(v-m.a[i])/m.length),ref=Math.abs(d[1])>.95?[1,0,0]:[0,1,0];let u=[d[1]*ref[2]-d[2]*ref[1],d[2]*ref[0]-d[0]*ref[2],d[0]*ref[1]-d[1]*ref[0]];const len=Math.hypot(...u);u=u.map(x=>x/len);const v=[d[1]*u[2]-d[2]*u[1],d[2]*u[0]-d[0]*u[2],d[0]*u[1]-d[1]*u[0]];return {d,u,v};}
export function memberVertices(m){const {u,v}=memberBasis(m),profile=PROFILES[m.kind];return [m.a,m.b].flatMap(a=>[[-1,-1],[1,-1],[1,1],[-1,1]].map(([su,sv])=>a.map((x,i)=>x+u[i]*su*profile.width/2+v[i]*sv*profile.depth/2)));}
export function exportOBJ(model){let out='# SteelSmart concept model; metres; member envelopes, not fabrication solids\n',offset=1;for(const m of model.members){out+=`o ${m.id}_${m.kind}\n`;out+=memberVertices(m).map(v=>'v '+v.map(x=>x.toFixed(6)).join(' ')).join('\n')+'\n';for(const face of [[1,4,3,2],[5,6,7,8],[1,2,6,5],[2,3,7,6],[3,4,8,7],[4,1,5,8]])out+='f '+face.map(i=>i+offset-1).join(' ')+'\n';offset+=8;}return out;}
export function exportCSV(model){return 'Member,Profile,Quantity,Total length (m),Mass (kg)\n'+billOfMaterials(model).map(r=>[r.kind,r.profile,r.quantity,r.length.toFixed(3),r.mass.toFixed(2)].join(',')).join('\n');}
