import * as THREE from './vendor/three.module.js';
import {PROFILES,memberBasis} from './model.js';
import {bindPointerDrag} from './pointer-drag.js';

export class SteelViewport {
  constructor(canvas,container,onSelect){
    this.active=true;this.frame=null;this.geometryPool=new Map();this.viewButtons=[...document.querySelectorAll('[data-view]')];
    this.canvas=canvas;this.container=container;this.onSelect=onSelect;this.yaw=-.66;this.pitch=.48;this.zoom=1;this.auto=false;this.exploded=false;this.wire=false;this.showDimensions=true;this.dirty=true;this.isolation=null;this.colorByMass=false;this.massMaterials=[];this.focusId=null;
    this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0xf1f3f6);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.autoUpdate=false;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.3;
    this.scene=new THREE.Scene();this.scene.fog=new THREE.Fog(0xf1f3f6,90,220);this.camera=new THREE.OrthographicCamera(-25,25,20,-20,.1,500);this.scene.add(new THREE.HemisphereLight(0xf7faff,0x7c879f,2.8));
    const light=new THREE.DirectionalLight(0xfff9ed,4.5);light.position.set(-20,45,20);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-55,right:55,top:55,bottom:-55,near:1,far:120});light.shadow.bias=-.0005;light.shadow.normalBias=.06;this.scene.add(light);const fill=new THREE.DirectionalLight(0xc1d5ff,1.8);fill.position.set(30,10,-20);this.scene.add(fill);
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(250,250),new THREE.MeshStandardMaterial({color:0xeef1f5,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.075;floor.receiveShadow=true;this.scene.add(floor);
    this.grid=new THREE.GridHelper(160,80,0xcfd6e1,0xdfe4ed);this.grid.material.transparent=true;this.grid.material.opacity=.65;this.grid.position.y=-.058;this.scene.add(this.grid);
    this.group=new THREE.Group();this.scene.add(this.group);this.dimensions=new THREE.Group();this.scene.add(this.dimensions);this.material=new THREE.MeshStandardMaterial({color:0x4b6084,roughness:.48,metalness:.6});this.purlinMaterial=new THREE.MeshStandardMaterial({color:0x7489ab,roughness:.54,metalness:.55});this.braceMaterial=new THREE.MeshStandardMaterial({color:0x7c8b9f,roughness:.6,metalness:.7});this.plateMaterial=new THREE.MeshStandardMaterial({color:0x526887,roughness:.5,metalness:.6});this.boltMaterial=new THREE.MeshStandardMaterial({color:0xa7afbb,roughness:.28,metalness:.85});this.selectedMaterial=new THREE.MeshStandardMaterial({color:0xe36d3b,roughness:.45,metalness:.4});this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.pickables=[];
    this.measureGroup=new THREE.Group();this.scene.add(this.measureGroup);this.measureLabel=document.createElement('span');this.measureLabel.className='measure-label';this.measureLabel.hidden=true;container.append(this.measureLabel);
    this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.visibility=new IntersectionObserver(entries=>{this.active=entries.at(-1).isIntersecting;this.lastFrameTime=null;if(this.active)this.dirty=true;else this.stopFrame();});this.visibility.observe(container);document.addEventListener('visibilitychange',()=>{this.lastFrameTime=null;if(document.hidden)this.stopFrame();else this.dirty=true;});this.bind();
  }
  get dirty(){return this._dirty;}
  set dirty(value){this._dirty=value;if(value)this.requestRender();}
  get auto(){return this._auto;}
  set auto(value){this._auto=value;this.lastFrameTime=null;if(value)this.dirty=true;}
  requestRender(){if(this.frame!=null||!this.renderer||!this.model||!this.active||document.hidden||this.contextLost)return;this.frame=requestAnimationFrame(time=>this.loop(time));}
  stopFrame(){if(this.frame!=null)cancelAnimationFrame(this.frame);this.frame=null;}
  geometry(key,create){if(!this.geometryPool.has(key))this.geometryPool.set(key,create());return this.geometryPool.get(key);}
  cylinder(radius,height,segments){return this.geometry(`cylinder:${radius}:${height}:${segments}`,()=>new THREE.CylinderGeometry(radius,radius,height,segments));}
  clear(group){const geometries=new Set();for(const child of [...group.children]){child.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.isLine)o.material.dispose();});group.remove(child);}for(const geometry of geometries)geometry.dispose();}
  meshBox(w,h,d,material,parent=this.group){const geometry=this.geometry(`box:${w}:${h}:${d}`,()=>new THREE.BoxGeometry(w,h,d)),mesh=new THREE.Mesh(geometry,material);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
  update(model){this.focusId=null;this.model=model;for(const material of this.massMaterials)material.dispose();this.massMaterials=[];this.clear(this.group);this.geometryPool.clear();this.clear(this.dimensions);this.pickables=[];this.selected=null;this.onSelect(null);const q=new THREE.Quaternion(),axis=new THREE.Vector3(0,1,0);
    for(const member of model.members){const a=new THREE.Vector3(...member.a),b=new THREE.Vector3(...member.b),length=member.length,p=PROFILES[member.kind],g=new THREE.Group();g.position.copy(a).add(b).multiplyScalar(.5);const basis=memberBasis(member);q.setFromRotationMatrix(new THREE.Matrix4().makeBasis(new THREE.Vector3(...basis.u),new THREE.Vector3(...basis.d),new THREE.Vector3(...basis.v).negate()));g.quaternion.copy(q);g.userData={member,base:g.position.clone()};this.group.add(g);let meshes=[];
      if(['column','rafter','beam'].includes(member.kind)){meshes.push(this.meshBox(p.web,length,p.depth,this.material,g));for(const sign of [-1,1]){const m=this.meshBox(p.width,length,p.flange,this.material,g);m.position.z=sign*(p.depth-p.flange)/2;meshes.push(m);}}
      else if(member.kind==='brace'){const mesh=new THREE.Mesh(this.cylinder(.025,length,6),this.braceMaterial);mesh.castShadow=true;g.add(mesh);meshes.push(mesh);}else meshes.push(this.meshBox(p.width,length,p.depth,this.purlinMaterial,g));
      for(const mesh of meshes){mesh.userData.member=member;mesh.userData.baseMaterial=mesh.material;this.pickables.push(mesh);}if(['column','rafter','beam'].includes(member.kind)){for(const sign of [-1,1]){const plate=this.meshBox(p.width+.07,.026,p.depth+.07,this.plateMaterial,g);plate.position.y=sign*(length/2-.025);for(const x of [-1,1])for(const z of [-1,1]){const bolt=new THREE.Mesh(this.cylinder(.019,.035,6),this.boltMaterial);bolt.position.set(x*(p.width/2-.018),sign*(length/2),z*(p.depth/2-.025));g.add(bolt);}}}
    }
    for(const plate of model.plates){const m=this.meshBox(.48,.055,.48,this.plateMaterial);m.position.set(...plate.position);m.userData.base=m.position.clone();for(const x of [-.16,.16])for(const z of [-.16,.16]){const bolt=new THREE.Mesh(this.cylinder(.025,.09,6),this.boltMaterial);bolt.position.set(plate.position[0]+x,.085,plate.position[2]+z);this.group.add(bolt);bolt.userData.base=bolt.position.clone();}}
    this.setExploded(this.exploded);this.setWireframe(this.wire);this.buildDimensions();this.setIsolation(this.isolation);this.paintMembers();this.setMeasurement(null,null);if(this.person)this.person.position.set(model.params.width/2+1.3,0,model.params.length/2);this.resize();this.dirty=true;
  }
  buildDimensions(){const {width:w,length:l,height:h}=this.model.params;this.labelPoints=[{p:[0,.02,l/2+2.3],text:`${w.toFixed(1)} m`},{p:[w/2+2.3,.02,0],text:`${l.toFixed(1)} m`},{p:[-w/2-1.7,h/2,l/2],text:`${h.toFixed(1)} m`}];const color=new THREE.LineBasicMaterial({color:0x9aa9bd,transparent:true,opacity:.65});const line=(a,b)=>{const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a),new THREE.Vector3(...b)]);this.dimensions.add(new THREE.Line(g,color.clone()));};const dim=(a,b,tick)=>{line(a,b);for(const p of [a,b])line(p.map((v,i)=>v-tick[i]),p.map((v,i)=>v+tick[i]));};dim([-w/2,0,l/2+2.3],[w/2,0,l/2+2.3],[.18,0,.25]);dim([w/2+2.3,0,-l/2],[w/2+2.3,0,l/2],[.25,0,.18]);dim([-w/2-1.7,0,l/2],[-w/2-1.7,h,l/2],[.25,0,0]);color.dispose();const labels=document.getElementById('dimension-labels');labels.replaceChildren();this.labelPoints.forEach(item=>{item.el=document.createElement('span');item.el.className='dimension-label';item.el.textContent=item.text;labels.append(item.el);});this.dimensions.visible=this.showDimensions;labels.hidden=!this.showDimensions;}
  resize(){const {width,height}=this.container.getBoundingClientRect();if(!width||!height)return;this.renderer.setSize(width,height,false);this.width=width;this.height=height;this.camera.aspect=width/height;this.positionCamera();this.dirty=true;}
  positionCamera(){
    if(!this.model||!this.width||!this.height)return;
    const {width:w,length:l,height:h}=this.model.params,aspect=this.width/this.height,extra=this.exploded?3:0,top=h+this.model.rise+extra,spread=this.exploded?1.12:1;
    let target=new THREE.Vector3(0,top/2,0),xs=[-w*spread/2-2.5,w*spread/2+2.5],ys=[-.4,top+.5],zs=[-l*spread/2-2.5,l*spread/2+2.5];
    const member=this.focusId&&this.model.members.find(m=>m.id===this.focusId);
    if(member){const group=this.group.children.find(g=>g.userData.member?.id===member.id),offset=group.position.clone().sub(group.userData.base);target=new THREE.Vector3(...member.a).add(new THREE.Vector3(...member.b)).multiplyScalar(.5).add(offset);const extent=i=>[Math.min(member.a[i],member.b[i])+offset.getComponent(i)-.6,Math.max(member.a[i],member.b[i])+offset.getComponent(i)+.6];xs=extent(0);ys=extent(1);zs=extent(2);}
    const r=90;this.camera.position.set(target.x+Math.sin(this.yaw)*Math.cos(this.pitch)*r,target.y+Math.sin(this.pitch)*r,target.z+Math.cos(this.yaw)*Math.cos(this.pitch)*r);this.camera.lookAt(target);this.camera.updateMatrixWorld();let maxX=0,maxY=0;
    for(const x of xs)for(const y of ys)for(const z of zs){const p=new THREE.Vector3(x,y,z).applyMatrix4(this.camera.matrixWorldInverse);maxX=Math.max(maxX,Math.abs(p.x));maxY=Math.max(maxY,Math.abs(p.y));}
    const half=Math.max(maxX/aspect,maxY,.5)*1.16/this.zoom;Object.assign(this.camera,{left:-half*aspect,right:half*aspect,top:half,bottom:-half});this.camera.updateProjectionMatrix();this.syncNamedView();this.dirty=true;
  }
  syncNamedView(){const yaw=Math.atan2(Math.sin(this.yaw),Math.cos(this.yaw)),name=[['front',0,.015],['top',0,Math.PI/2-.001],['perspective',-.66,.48]].find(([,y,p])=>Math.abs(yaw-y)<1e-5&&Math.abs(this.pitch-p)<1e-5)?.[0]||null;if(name===this.namedView)return;this.namedView=name;for(const button of this.viewButtons){const active=button.dataset.view===name;button.classList.toggle('selected',active);button.setAttribute('aria-pressed',active);}}
  setView(view){this.auto=false;document.getElementById('rotate').setAttribute('aria-pressed','false');this.focusId=null;if(view==='front'){this.yaw=0;this.pitch=.015;}else if(view==='top'){this.yaw=0;this.pitch=Math.PI/2-.001;}else{this.yaw=-.66;this.pitch=.48;}this.zoom=1;this.positionCamera();}
  fit(){this.focusId=null;this.zoom=1;this.positionCamera();}
  setWireframe(value){this.renderer.shadowMap.needsUpdate=true;this.wire=value;for(const m of [this.material,this.purlinMaterial,this.braceMaterial,this.plateMaterial,this.boltMaterial,this.selectedMaterial,...this.massMaterials])m.wireframe=value;this.dirty=true;}
  setExploded(value){this.renderer.shadowMap.needsUpdate=true;this.exploded=value;for(const g of this.group.children){const base=g.userData.base;if(base){g.position.copy(base);if(value){g.position.x*=1.12;g.position.z*=1.12;if(g.userData.member?.kind!=='column')g.position.y+=g.userData.member?.kind==='purlin'?3:1.5;}}}this.positionCamera();this.dirty=true;}
  setDimensions(value){this.showDimensions=value;this.dimensions.visible=value;document.getElementById('dimension-labels').hidden=!value;this.dirty=true;}
  selectMember(id){
    const member=this.model?.members.find(m=>m.id===id)||null;
    if(member&&this.isolation&&member.kind!==this.isolation)this.setIsolation(null);
    this.selected=member;this.paintMembers();this.onSelect(member);this.dirty=true;
  }
  select(event){
    const rect=this.canvas.getBoundingClientRect();this.pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);
    const visible=this.pickables.filter(mesh=>mesh.parent.visible),hit=this.raycaster.intersectObjects(visible,false)[0];this.selectMember(hit?.object.userData.member.id);
  }
  setIsolation(kind){
    this.renderer.shadowMap.needsUpdate=true;
    this.isolation=kind&&this.model?.members.some(member=>member.kind===kind)?kind:null;for(const child of this.group.children)child.visible=!this.isolation||child.userData.member?.kind===this.isolation;
    if(this.selected&&this.isolation&&this.selected.kind!==this.isolation){this.selected=null;this.paintMembers();this.onSelect(null);}this.dirty=true;
  }
  paintMembers(){
    if(!this.model)return;
    const masses=this.model.members.map(m=>m.mass),lo=Math.min(...masses),hi=Math.max(...masses);
    for(const mesh of this.pickables){if(this.colorByMass&&!mesh.userData.massMaterial){const t=(mesh.userData.member.mass-lo)/(hi-lo||1),color=new THREE.Color(0x527ba4).lerp(new THREE.Color(0xea6b36),t),material=new THREE.MeshStandardMaterial({color,roughness:.65,metalness:.25,wireframe:this.wire});mesh.userData.massMaterial=material;this.massMaterials.push(material);}mesh.material=this.selected?.id===mesh.userData.member.id?this.selectedMaterial:this.colorByMass?mesh.userData.massMaterial:mesh.userData.baseMaterial;}this.dirty=true;
  }
  setColorByMass(value){this.colorByMass=value;this.paintMembers();}
  focusMember(id){if(!this.model.members.some(m=>m.id===id))return;this.focusId=id;this.zoom=1;this.positionCamera();}
  getCameraState(){return {yaw:Math.atan2(Math.sin(this.yaw),Math.cos(this.yaw)),pitch:this.pitch,zoom:this.zoom,focusId:this.focusId};}
  restoreCamera(view){if(!view)return;for(const [key,lo,hi] of [['yaw',-Math.PI*2,Math.PI*2],['pitch',.001,Math.PI/2-.001],['zoom',.45,3]])if(Number.isFinite(view[key]))this[key]=Math.max(lo,Math.min(hi,view[key]));this.focusId=this.model.members.some(m=>m.id===view.focusId)?view.focusId:null;this.positionCamera();}
  setMeasurement(a,b){
    this.measureGroup.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});this.measureGroup.clear();this.measureLabel.hidden=!a||!b;this.measurePoints=null;
    if(a&&b){this.measurePoints=[a.position,b.position];const points=this.measurePoints.map(p=>new THREE.Vector3(...p)),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineDashedMaterial({color:0xd94d2b,dashSize:.28,gapSize:.13,depthTest:false}));line.computeLineDistances();line.renderOrder=10;this.measureGroup.add(line);for(const point of points){const dot=new THREE.Mesh(new THREE.SphereGeometry(.095,10,8),new THREE.MeshBasicMaterial({color:0xd94d2b,depthTest:false}));dot.position.copy(point);dot.renderOrder=11;this.measureGroup.add(dot);}this.measureLabel.textContent=points[0].distanceTo(points[1]).toFixed(3)+' m';}this.dirty=true;
  }
  setScaleReference(value){
    this.renderer.shadowMap.needsUpdate=true;
    if(value&&!this.person){this.person=new THREE.Group();const material=new THREE.MeshStandardMaterial({color:0xbc6947,roughness:.95}),part=(geometry,x,y,z)=>{const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=true;this.person.add(mesh);return mesh;};part(new THREE.SphereGeometry(.105,12,10),0,1.645,0);part(new THREE.BoxGeometry(.34,.55,.17),0,1.265,0);for(const sign of [-1,1]){part(new THREE.CylinderGeometry(.067,.055,.8,8),sign*.09,.55,0);part(new THREE.BoxGeometry(.11,.075,.23),sign*.09,.038,.04);const arm=part(new THREE.CylinderGeometry(.045,.05,.55,8),sign*.24,1.22,0);arm.rotation.z=sign*.1;}this.scene.add(this.person);}
    if(this.person){this.person.visible=value;this.person.position.set(this.model.params.width/2+1.3,0,this.model.params.length/2);}this.dirty=true;
  }
  bind(){this.unbindDrag=bindPointerDrag(this.canvas,{canStart:()=>!this.contextLost,onStart:()=>this.container.focus({preventScroll:true}),onMove:(dx,dy)=>{this.yaw-=dx*.007;this.pitch=Math.max(.04,Math.min(1.55,this.pitch+dy*.006));this.positionCamera();},onEnd:(event,total,cancelled)=>{if(!cancelled&&total<5)this.select(event);}});this.container.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(.45,Math.min(3,this.zoom*Math.exp(-e.deltaY*.001)));this.positionCamera();},{passive:false});this.container.addEventListener('keydown',e=>{if(e.target!==this.container)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','+','-'].includes(e.key)){e.preventDefault();if(e.key==='Home')this.setView('perspective');if(e.key==='ArrowLeft')this.yaw-=.1;if(e.key==='ArrowRight')this.yaw+=.1;if(e.key==='ArrowUp')this.pitch=Math.min(1.55,this.pitch+.1);if(e.key==='ArrowDown')this.pitch=Math.max(.04,this.pitch-.1);if(e.key==='+')this.zoom=Math.min(3,this.zoom*1.1);if(e.key==='-')this.zoom=Math.max(.45,this.zoom/1.1);this.positionCamera();}});this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.contextLost=true;this.stopFrame();this.canvas.dispatchEvent(new CustomEvent('viewportavailability',{detail:false}));document.getElementById('viewport-error').hidden=false;document.getElementById('viewport-error').textContent='The graphics context was interrupted. Reload this page to restore the 3D view. Your saved parameters are kept.';});this.canvas.addEventListener('webglcontextrestored',()=>{this.contextLost=false;document.getElementById('viewport-error').hidden=true;this.renderer.shadowMap.needsUpdate=true;this.resize();this.canvas.dispatchEvent(new CustomEvent('viewportavailability',{detail:true}));});}
  loop(time){this.frame=null;if(document.hidden||!this.active||this.contextLost)return;if(this.auto){const elapsed=this.lastFrameTime==null?16.67:Math.min(50,time-this.lastFrameTime);this.lastFrameTime=time;this.yaw+=elapsed*.00012;this.positionCamera();}if(!this.dirty)return;this.renderer.render(this.scene,this.camera);for(const item of this.labelPoints||[]){const p=new THREE.Vector3(...item.p).project(this.camera);item.el.style.left=((p.x+1)/2*this.width)+'px';item.el.style.top=((-p.y+1)/2*this.height)+'px';item.el.style.visibility=Math.abs(p.x)>1||Math.abs(p.y)>1?'hidden':'visible';}if(this.measurePoints){const midpoint=new THREE.Vector3(...this.measurePoints[0]).add(new THREE.Vector3(...this.measurePoints[1])).multiplyScalar(.5).project(this.camera);this.measureLabel.style.left=((midpoint.x+1)/2*this.width)+'px';this.measureLabel.style.top=((-midpoint.y+1)/2*this.height)+'px';this.measureLabel.style.visibility=Math.abs(midpoint.x)>1||Math.abs(midpoint.y)>1?'hidden':'visible';}this.dirty=false;}
}
